FROM node:16.13-alpine as builder

RUN apk update && apk add python3 make g++

WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json

RUN npm install -f

COPY . .

RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY /docker-nginx.conf /etc/nginx/conf.d

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]